eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
        - id: users
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**
        - id: carts
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/carts/**
management:
  tracing:
    sampling:
      probability: 1.0
